-- ==================================================
-- SQL Portfolio Project: Sales & Retail Analytics
-- Author: Zohaib Sattar
-- Dataset: sales_dataset_30days.csv
-- Purpose: 1-Month Daily SQL Practice
-- ==================================================
